<?php 
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Character implements JsonSerializable {
    /**
     * A resource list containing comics which feature this character.
     * @required
     * @var ComicList $comics public property
     */
    public $comics;

    /**
     * A short bio or description of the character.
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * A resource list of events in which this character appears.
     * @required
     * @var EventList $events public property
     */
    public $events;

    /**
     * The unique ID of the character resource.
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var string $modified public property
     */
    public $modified;

    /**
     * The name of the character.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var string $resourceURI public property
     */
    public $resourceURI;

    /**
     * A resource list of series in which this character appears.
     * @required
     * @var SeriesList $series public property
     */
    public $series;

    /**
     * A resource list of stories in which this character appears.
     * @required
     * @var StoryList $stories public property
     */
    public $stories;

    /**
     * The representative image for this character.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * A set of public web site URLs for the resource.
     * @required
     * @var Url[] $urls public property
     */
    public $urls;

    /**
     * Constructor to set initial or default values of member properties
     * @param   ComicList         $comics        Initialization value for the property $this->comics     
     * @param   string            $description   Initialization value for the property $this->description
     * @param   EventList         $events        Initialization value for the property $this->events     
     * @param   integer           $id            Initialization value for the property $this->id         
     * @param   string            $modified      Initialization value for the property $this->modified   
     * @param   string            $name          Initialization value for the property $this->name       
     * @param   string            $resourceURI   Initialization value for the property $this->resourceURI
     * @param   SeriesList        $series        Initialization value for the property $this->series     
     * @param   StoryList         $stories       Initialization value for the property $this->stories    
     * @param   Thumbnail         $thumbnail     Initialization value for the property $this->thumbnail  
     * @param   array             $urls          Initialization value for the property $this->urls       
     */
    public function __construct()
    {
        if(11 == func_num_args())
        {
            $this->comics      = func_get_arg(0);
            $this->description = func_get_arg(1);
            $this->events      = func_get_arg(2);
            $this->id          = func_get_arg(3);
            $this->modified    = func_get_arg(4);
            $this->name        = func_get_arg(5);
            $this->resourceURI = func_get_arg(6);
            $this->series      = func_get_arg(7);
            $this->stories     = func_get_arg(8);
            $this->thumbnail   = func_get_arg(9);
            $this->urls        = func_get_arg(10);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['comics']      = $this->comics;
        $json['description'] = $this->description;
        $json['events']      = $this->events;
        $json['id']          = $this->id;
        $json['modified']    = $this->modified;
        $json['name']        = $this->name;
        $json['resourceURI'] = $this->resourceURI;
        $json['series']      = $this->series;
        $json['stories']     = $this->stories;
        $json['thumbnail']   = $this->thumbnail;
        $json['urls']        = $this->urls;

        return $json;
    }
}