<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ComicPrice implements JsonSerializable
{
    /**
     * A description of the price (e.g. print price, digital price).
     * @required
     * @var object $type public property
     */
    public $type;

    /**
     * The price (all prices in USD).
     * @required
     * @var object $price public property
     */
    public $price;

    /**
     * Constructor to set initial or default values of member properties
     * @param object $type  Initialization value for $this->type
     * @param object $price Initialization value for $this->price
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->type  = func_get_arg(0);
            $this->price = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']  = $this->type;
        $json['price'] = $this->price;

        return $json;
    }
}
