<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ComicDate implements JsonSerializable
{
    /**
     * A description of the date (e.g. onsale date, FOC date).
     * @required
     * @var object $type public property
     */
    public $type;

    /**
     * The date.
     * @required
     * @var object $date public property
     */
    public $date;

    /**
     * Constructor to set initial or default values of member properties
     * @param object $type Initialization value for $this->type
     * @param object $date Initialization value for $this->date
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->type = func_get_arg(0);
            $this->date = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type'] = $this->type;
        $json['date'] = $this->date;

        return $json;
    }
}
