<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Comic implements JsonSerializable
{
    /**
     * The unique ID of the comic resource.
     * @required
     * @var object $id public property
     */
    public $id;

    /**
     * The ID of the digital comic representation of this comic. Will be 0 if the comic is not available digitally.
     * @required
     * @var object $digitalId public property
     */
    public $digitalId;

    /**
     * The canonical title of the comic.
     * @required
     * @var object $title public property
     */
    public $title;

    /**
     * The number of the issue in the series (will generally be 0 for collection formats).
     * @required
     * @var object $issueNumber public property
     */
    public $issueNumber;

    /**
     * If the issue is a variant (e.g. an alternate cover, second printing, or director’s cut), a text description of the variant.
     * @required
     * @var object $variantDescription public property
     */
    public $variantDescription;

    /**
     * The preferred description of the comic.
     * @required
     * @var object $description public property
     */
    public $description;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var object $modified public property
     */
    public $modified;

    /**
     * The ISBN for the comic (generally only populated for collection formats).
     * @required
     * @var object $isbn public property
     */
    public $isbn;

    /**
     * The UPC barcode number for the comic (generally only populated for periodical formats).
     * @required
     * @var object $upc public property
     */
    public $upc;

    /**
     * The Diamond code for the comic.
     * @required
     * @var object $diamondCode public property
     */
    public $diamondCode;

    /**
     * The EAN barcode for the comic.
     * @required
     * @var object $ean public property
     */
    public $ean;

    /**
     * The ISSN barcode for the comic.
     * @required
     * @var object $issn public property
     */
    public $issn;

    /**
     * The publication format of the comic e.g. comic, hardcover, trade paperback.
     * @required
     * @var object $format public property
     */
    public $format;

    /**
     * The number of story pages in the comic.
     * @required
     * @var object $pageCount public property
     */
    public $pageCount;

    /**
     * A set of descriptive text blurbs for the comic.
     * @required
     * @var TextObject[] $textObjects public property
     */
    public $textObjects;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var object $resourceURI public property
     */
    public $resourceURI;

    /**
     * A set of public web site URLs for the resource.
     * @required
     * @var Url[] $urls public property
     */
    public $urls;

    /**
     * A summary representation of the series to which this comic belongs.
     * @required
     * @var SeriesSummary $series public property
     */
    public $series;

    /**
     * A list of variant issues for this comic (includes the "original" issue if the current issue is a variant).
     * @required
     * @var ComicSummary[] $variants public property
     */
    public $variants;

    /**
     * A list of collections which include this comic (will generally be empty if the comic's format is a collection).
     * @required
     * @var ComicSummary[] $collections public property
     */
    public $collections;

    /**
     * A list of issues collected in this comic (will generally be empty for periodical formats such as "comic" or "magazine").
     * @required
     * @var ComicSummary[] $collectedIssues public property
     */
    public $collectedIssues;

    /**
     * A list of key dates for this comic.
     * @required
     * @var ComicDate[] $dates public property
     */
    public $dates;

    /**
     * A list of prices for this comic.
     * @required
     * @var ComicPrice[] $prices public property
     */
    public $prices;

    /**
     * The representative image for this comic.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * A list of promotional images associated with this comic.
     * @required
     * @var Image[] $images public property
     */
    public $images;

    /**
     * A resource list containing the creators associated with this comic.
     * @required
     * @var CreatorList $creators public property
     */
    public $creators;

    /**
     * A resource list containing the characters which appear in this comic.
     * @required
     * @var CharacterList $characters public property
     */
    public $characters;

    /**
     * A resource list containing the stories which appear in this comic.
     * @required
     * @var StoryList $stories public property
     */
    public $stories;

    /**
     * A resource list containing the events in which this comic appears.
     * @required
     * @var EventList $events public property
     */
    public $events;

    /**
     * Constructor to set initial or default values of member properties
     * @param object        $id                 Initialization value for $this->id
     * @param object        $digitalId          Initialization value for $this->digitalId
     * @param object        $title              Initialization value for $this->title
     * @param object        $issueNumber        Initialization value for $this->issueNumber
     * @param object        $variantDescription Initialization value for $this->variantDescription
     * @param object        $description        Initialization value for $this->description
     * @param object        $modified           Initialization value for $this->modified
     * @param object        $isbn               Initialization value for $this->isbn
     * @param object        $upc                Initialization value for $this->upc
     * @param object        $diamondCode        Initialization value for $this->diamondCode
     * @param object        $ean                Initialization value for $this->ean
     * @param object        $issn               Initialization value for $this->issn
     * @param object        $format             Initialization value for $this->format
     * @param object        $pageCount          Initialization value for $this->pageCount
     * @param array         $textObjects        Initialization value for $this->textObjects
     * @param object        $resourceURI        Initialization value for $this->resourceURI
     * @param array         $urls               Initialization value for $this->urls
     * @param SeriesSummary $series             Initialization value for $this->series
     * @param array         $variants           Initialization value for $this->variants
     * @param array         $collections        Initialization value for $this->collections
     * @param array         $collectedIssues    Initialization value for $this->collectedIssues
     * @param array         $dates              Initialization value for $this->dates
     * @param array         $prices             Initialization value for $this->prices
     * @param Thumbnail     $thumbnail          Initialization value for $this->thumbnail
     * @param array         $images             Initialization value for $this->images
     * @param CreatorList   $creators           Initialization value for $this->creators
     * @param CharacterList $characters         Initialization value for $this->characters
     * @param StoryList     $stories            Initialization value for $this->stories
     * @param EventList     $events             Initialization value for $this->events
     */
    public function __construct()
    {
        if (29 == func_num_args()) {
            $this->id                 = func_get_arg(0);
            $this->digitalId          = func_get_arg(1);
            $this->title              = func_get_arg(2);
            $this->issueNumber        = func_get_arg(3);
            $this->variantDescription = func_get_arg(4);
            $this->description        = func_get_arg(5);
            $this->modified           = func_get_arg(6);
            $this->isbn               = func_get_arg(7);
            $this->upc                = func_get_arg(8);
            $this->diamondCode        = func_get_arg(9);
            $this->ean                = func_get_arg(10);
            $this->issn               = func_get_arg(11);
            $this->format             = func_get_arg(12);
            $this->pageCount          = func_get_arg(13);
            $this->textObjects        = func_get_arg(14);
            $this->resourceURI        = func_get_arg(15);
            $this->urls               = func_get_arg(16);
            $this->series             = func_get_arg(17);
            $this->variants           = func_get_arg(18);
            $this->collections        = func_get_arg(19);
            $this->collectedIssues    = func_get_arg(20);
            $this->dates              = func_get_arg(21);
            $this->prices             = func_get_arg(22);
            $this->thumbnail          = func_get_arg(23);
            $this->images             = func_get_arg(24);
            $this->creators           = func_get_arg(25);
            $this->characters         = func_get_arg(26);
            $this->stories            = func_get_arg(27);
            $this->events             = func_get_arg(28);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                 = $this->id;
        $json['digitalId']          = $this->digitalId;
        $json['title']              = $this->title;
        $json['issueNumber']        = $this->issueNumber;
        $json['variantDescription'] = $this->variantDescription;
        $json['description']        = $this->description;
        $json['modified']           = $this->modified;
        $json['isbn']               = $this->isbn;
        $json['upc']                = $this->upc;
        $json['diamondCode']        = $this->diamondCode;
        $json['ean']                = $this->ean;
        $json['issn']               = $this->issn;
        $json['format']             = $this->format;
        $json['pageCount']          = $this->pageCount;
        $json['textObjects']        = $this->textObjects;
        $json['resourceURI']        = $this->resourceURI;
        $json['urls']               = $this->urls;
        $json['series']             = $this->series;
        $json['variants']           = $this->variants;
        $json['collections']        = $this->collections;
        $json['collectedIssues']    = $this->collectedIssues;
        $json['dates']              = $this->dates;
        $json['prices']             = $this->prices;
        $json['thumbnail']          = $this->thumbnail;
        $json['images']             = $this->images;
        $json['creators']           = $this->creators;
        $json['characters']         = $this->characters;
        $json['stories']            = $this->stories;
        $json['events']             = $this->events;

        return $json;
    }
}
