<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CreatorDataContainer implements JsonSerializable
{
    /**
     * The requested offset (number of skipped results) of the call.
     * @required
     * @var object $offset public property
     */
    public $offset;

    /**
     * The requested result limit.
     * @required
     * @var object $limit public property
     */
    public $limit;

    /**
     * The total number of resources available given the current filter set.
     * @required
     * @var object $total public property
     */
    public $total;

    /**
     * The total number of results returned by this call.
     * @required
     * @var object $count public property
     */
    public $count;

    /**
     * The list of creators returned by the call.
     * @required
     * @var Creator[] $results public property
     */
    public $results;

    /**
     * Constructor to set initial or default values of member properties
     * @param object $offset  Initialization value for $this->offset
     * @param object $limit   Initialization value for $this->limit
     * @param object $total   Initialization value for $this->total
     * @param object $count   Initialization value for $this->count
     * @param array  $results Initialization value for $this->results
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->offset  = func_get_arg(0);
            $this->limit   = func_get_arg(1);
            $this->total   = func_get_arg(2);
            $this->count   = func_get_arg(3);
            $this->results = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['offset']  = $this->offset;
        $json['limit']   = $this->limit;
        $json['total']   = $this->total;
        $json['count']   = $this->count;
        $json['results'] = $this->results;

        return $json;
    }
}
