<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CreatorSummary implements JsonSerializable
{
    /**
     * The path to the individual creator resource.
     * @required
     * @var object $resourceURI public property
     */
    public $resourceURI;

    /**
     * The full name of the creator.
     * @required
     * @var object $name public property
     */
    public $name;

    /**
     * The role of the creator in the parent entity.
     * @required
     * @var object $role public property
     */
    public $role;

    /**
     * Constructor to set initial or default values of member properties
     * @param object $resourceURI Initialization value for $this->resourceURI
     * @param object $name        Initialization value for $this->name
     * @param object $role        Initialization value for $this->role
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->resourceURI = func_get_arg(0);
            $this->name        = func_get_arg(1);
            $this->role        = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['resourceURI'] = $this->resourceURI;
        $json['name']        = $this->name;
        $json['role']        = $this->role;

        return $json;
    }
}
