<?php 
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Creator implements JsonSerializable {
    /**
     * The unique ID of the creator resource.
     * @required
     * @var int $id public property
     */
    public $id;

    /**
     * The first name of the creator.
     * @required
     * @var string $firstName public property
     */
    public $firstName;

    /**
     * The middle name of the creator.
     * @required
     * @var string $middleName public property
     */
    public $middleName;

    /**
     * The last name of the creator.
     * @required
     * @var string $lastName public property
     */
    public $lastName;

    /**
     * The suffix or honorific for the creator.
     * @required
     * @var string $suffix public property
     */
    public $suffix;

    /**
     * The full name of the creator (a space-separated concatenation of the above four fields).
     * @required
     * @var string $fullName public property
     */
    public $fullName;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var string $modified public property
     */
    public $modified;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var string $resourceURI public property
     */
    public $resourceURI;

    /**
     * A set of public web site URLs for the resource.
     * @required
     * @var array $urls public property
     */
    public $urls;

    /**
     * The representative image for this creator.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * A resource list containing the series which feature work by this creator.
     * @required
     * @var SeriesList $series public property
     */
    public $series;

    /**
     * A resource list containing the stories which feature work by this creator.
     * @required
     * @var StoryList $stories public property
     */
    public $stories;

    /**
     * A resource list containing the comics which feature work by this creator.
     * @required
     * @var ComicList $comics public property
     */
    public $comics;

    /**
     * A resource list containing the events which feature work by this creator.
     * @required
     * @var EventList $events public property
     */
    public $events;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   int               $id            Initialization value for the property $this->id         
	 * @param   string            $firstName     Initialization value for the property $this->firstName  
	 * @param   string            $middleName    Initialization value for the property $this->middleName 
	 * @param   string            $lastName      Initialization value for the property $this->lastName   
	 * @param   string            $suffix        Initialization value for the property $this->suffix     
	 * @param   string            $fullName      Initialization value for the property $this->fullName   
	 * @param   string            $modified      Initialization value for the property $this->modified   
	 * @param   string            $resourceURI   Initialization value for the property $this->resourceURI
	 * @param   array             $urls          Initialization value for the property $this->urls       
	 * @param   Thumbnail         $thumbnail     Initialization value for the property $this->thumbnail  
	 * @param   SeriesList        $series        Initialization value for the property $this->series     
	 * @param   StoryList         $stories       Initialization value for the property $this->stories    
	 * @param   ComicList         $comics        Initialization value for the property $this->comics     
	 * @param   EventList         $events        Initialization value for the property $this->events     
     */
    public function __construct()
    {
        if(14 == func_num_args())
        {
            $this->id          = func_get_arg(0);
            $this->firstName   = func_get_arg(1);
            $this->middleName  = func_get_arg(2);
            $this->lastName    = func_get_arg(3);
            $this->suffix      = func_get_arg(4);
            $this->fullName    = func_get_arg(5);
            $this->modified    = func_get_arg(6);
            $this->resourceURI = func_get_arg(7);
            $this->urls        = func_get_arg(8);
            $this->thumbnail   = func_get_arg(9);
            $this->series      = func_get_arg(10);
            $this->stories     = func_get_arg(11);
            $this->comics      = func_get_arg(12);
            $this->events      = func_get_arg(13);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']          = $this->id;
        $json['firstName']   = $this->firstName;
        $json['middleName']  = $this->middleName;
        $json['lastName']    = $this->lastName;
        $json['suffix']      = $this->suffix;
        $json['fullName']    = $this->fullName;
        $json['modified']    = $this->modified;
        $json['resourceURI'] = $this->resourceURI;
        $json['urls']        = $this->urls;
        $json['thumbnail']   = $this->thumbnail;
        $json['series']      = $this->series;
        $json['stories']     = $this->stories;
        $json['comics']      = $this->comics;
        $json['events']      = $this->events;

        return $json;
    }
}