<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */

namespace MarvelComicsLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class DateDescriptorEnum {
    /**
     * TODO: Write general description for this element
     */
    const LASTWEEK = "lastWeek";

    /**
     * TODO: Write general description for this element
     */
    const NEXTWEEK = "nextWeek";

    /**
     * TODO: Write general description for this element
     */
    const THISMONTH = "thisMonth";

    /**
     * TODO: Write general description for this element
     */
    const THISWEEK = "thisWeek";

}