<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Event implements JsonSerializable
{
    /**
     * The unique ID of the event resource.
     * @required
     * @var object $id public property
     */
    public $id;

    /**
     * The title of the event.
     * @required
     * @var object $title public property
     */
    public $title;

    /**
     * A description of the event.
     * @required
     * @var object $description public property
     */
    public $description;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var object $resourceURI public property
     */
    public $resourceURI;

    /**
     * A set of public web site URLs for the event.
     * @required
     * @var Url[] $urls public property
     */
    public $urls;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var object $modified public property
     */
    public $modified;

    /**
     * The date of publication of the first issue in this event.
     * @required
     * @var object $start public property
     */
    public $start;

    /**
     * The date of publication of the last issue in this event.
     * @required
     * @var object $end public property
     */
    public $end;

    /**
     * The representative image for this event.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * A resource list containing the comics in this event.
     * @required
     * @var ComicList $comics public property
     */
    public $comics;

    /**
     * A resource list containing the stories in this event.
     * @required
     * @var StoryList $stories public property
     */
    public $stories;

    /**
     * A resource list containing the series in this event.
     * @required
     * @var SeriesList $series public property
     */
    public $series;

    /**
     * A resource list containing the characters which appear in this event.
     * @required
     * @var CharacterList $characters public property
     */
    public $characters;

    /**
     * A resource list containing creators whose work appears in this event.
     * @required
     * @var CreatorList $creators public property
     */
    public $creators;

    /**
     * A summary representation of the event which follows this event.
     * @required
     * @var EventSummary $next public property
     */
    public $next;

    /**
     * A summary representation of the event which preceded this event.
     * @required
     * @var EventSummary $previous public property
     */
    public $previous;

    /**
     * Constructor to set initial or default values of member properties
     * @param object        $id          Initialization value for $this->id
     * @param object        $title       Initialization value for $this->title
     * @param object        $description Initialization value for $this->description
     * @param object        $resourceURI Initialization value for $this->resourceURI
     * @param array         $urls        Initialization value for $this->urls
     * @param object        $modified    Initialization value for $this->modified
     * @param object        $start       Initialization value for $this->start
     * @param object        $end         Initialization value for $this->end
     * @param Thumbnail     $thumbnail   Initialization value for $this->thumbnail
     * @param ComicList     $comics      Initialization value for $this->comics
     * @param StoryList     $stories     Initialization value for $this->stories
     * @param SeriesList    $series      Initialization value for $this->series
     * @param CharacterList $characters  Initialization value for $this->characters
     * @param CreatorList   $creators    Initialization value for $this->creators
     * @param EventSummary  $next        Initialization value for $this->next
     * @param EventSummary  $previous    Initialization value for $this->previous
     */
    public function __construct()
    {
        if (16 == func_num_args()) {
            $this->id          = func_get_arg(0);
            $this->title       = func_get_arg(1);
            $this->description = func_get_arg(2);
            $this->resourceURI = func_get_arg(3);
            $this->urls        = func_get_arg(4);
            $this->modified    = func_get_arg(5);
            $this->start       = func_get_arg(6);
            $this->end         = func_get_arg(7);
            $this->thumbnail   = func_get_arg(8);
            $this->comics      = func_get_arg(9);
            $this->stories     = func_get_arg(10);
            $this->series      = func_get_arg(11);
            $this->characters  = func_get_arg(12);
            $this->creators    = func_get_arg(13);
            $this->next        = func_get_arg(14);
            $this->previous    = func_get_arg(15);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']          = $this->id;
        $json['title']       = $this->title;
        $json['description'] = $this->description;
        $json['resourceURI'] = $this->resourceURI;
        $json['urls']        = $this->urls;
        $json['modified']    = $this->modified;
        $json['start']       = $this->start;
        $json['end']         = $this->end;
        $json['thumbnail']   = $this->thumbnail;
        $json['comics']      = $this->comics;
        $json['stories']     = $this->stories;
        $json['series']      = $this->series;
        $json['characters']  = $this->characters;
        $json['creators']    = $this->creators;
        $json['next']        = $this->next;
        $json['previous']    = $this->previous;

        return $json;
    }
}
