<?php 
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Image implements JsonSerializable {
    /**
     * The directory path of to the image.
     * @required
     * @var string $path public property
     */
    public $path;

    /**
     * The file extension for the image.
     * @required
     * @var string $extension public property
     */
    public $extension;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   string            $path        Initialization value for the property $this->path     
	 * @param   string            $extension   Initialization value for the property $this->extension
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->path      = func_get_arg(0);
            $this->extension = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['path']      = $this->path;
        $json['extension'] = $this->extension;

        return $json;
    }
}