<?php 
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Series implements JsonSerializable {
    /**
     * A resource list containing characters which appear in comics in this series.
     * @required
     * @var CharacterList $characters public property
     */
    public $characters;

    /**
     * A resource list containing comics in this series.
     * @required
     * @var ComicList $comics public property
     */
    public $comics;

    /**
     * A resource list of creators whose work appears in comics in this series.
     * @required
     * @var CreatorList $creators public property
     */
    public $creators;

    /**
     * A description of the series.
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * The last year of publication for the series (conventionally, 2099 for ongoing series) .
     * @required
     * @var integer $endYear public property
     */
    public $endYear;

    /**
     * A resource list containing events which take place in comics in this series.
     * @required
     * @var EventList $events public property
     */
    public $events;

    /**
     * The unique ID of the series resource.
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var string $modified public property
     */
    public $modified;

    /**
     * A summary representation of the series which follows this series.
     * @required
     * @var SeriesSummary $next public property
     */
    public $next;

    /**
     * A summary representation of the series which preceded this series.
     * @required
     * @var SeriesSummary $previous public property
     */
    public $previous;

    /**
     * The age-appropriateness rating for the series.
     * @required
     * @var string $rating public property
     */
    public $rating;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var string $resourceURI public property
     */
    public $resourceURI;

    /**
     * The first year of publication for the series.
     * @required
     * @var integer $startYear public property
     */
    public $startYear;

    /**
     * A resource list containing stories which occur in comics in this series.
     * @required
     * @var StoryList $stories public property
     */
    public $stories;

    /**
     * The representative image for this series.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * The canonical title of the series.
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * A set of public web site URLs for the resource.
     * @required
     * @var Url[] $urls public property
     */
    public $urls;

    /**
     * Constructor to set initial or default values of member properties
     * @param   CharacterList     $characters    Initialization value for the property $this->characters 
     * @param   ComicList         $comics        Initialization value for the property $this->comics     
     * @param   CreatorList       $creators      Initialization value for the property $this->creators   
     * @param   string            $description   Initialization value for the property $this->description
     * @param   integer           $endYear       Initialization value for the property $this->endYear    
     * @param   EventList         $events        Initialization value for the property $this->events     
     * @param   integer           $id            Initialization value for the property $this->id         
     * @param   string            $modified      Initialization value for the property $this->modified   
     * @param   SeriesSummary     $next          Initialization value for the property $this->next       
     * @param   SeriesSummary     $previous      Initialization value for the property $this->previous   
     * @param   string            $rating        Initialization value for the property $this->rating     
     * @param   string            $resourceURI   Initialization value for the property $this->resourceURI
     * @param   integer           $startYear     Initialization value for the property $this->startYear  
     * @param   StoryList         $stories       Initialization value for the property $this->stories    
     * @param   Thumbnail         $thumbnail     Initialization value for the property $this->thumbnail  
     * @param   string            $title         Initialization value for the property $this->title      
     * @param   array             $urls          Initialization value for the property $this->urls       
     */
    public function __construct()
    {
        if(17 == func_num_args())
        {
            $this->characters  = func_get_arg(0);
            $this->comics      = func_get_arg(1);
            $this->creators    = func_get_arg(2);
            $this->description = func_get_arg(3);
            $this->endYear     = func_get_arg(4);
            $this->events      = func_get_arg(5);
            $this->id          = func_get_arg(6);
            $this->modified    = func_get_arg(7);
            $this->next        = func_get_arg(8);
            $this->previous    = func_get_arg(9);
            $this->rating      = func_get_arg(10);
            $this->resourceURI = func_get_arg(11);
            $this->startYear   = func_get_arg(12);
            $this->stories     = func_get_arg(13);
            $this->thumbnail   = func_get_arg(14);
            $this->title       = func_get_arg(15);
            $this->urls        = func_get_arg(16);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['characters']  = $this->characters;
        $json['comics']      = $this->comics;
        $json['creators']    = $this->creators;
        $json['description'] = $this->description;
        $json['endYear']     = $this->endYear;
        $json['events']      = $this->events;
        $json['id']          = $this->id;
        $json['modified']    = $this->modified;
        $json['next']        = $this->next;
        $json['previous']    = $this->previous;
        $json['rating']      = $this->rating;
        $json['resourceURI'] = $this->resourceURI;
        $json['startYear']   = $this->startYear;
        $json['stories']     = $this->stories;
        $json['thumbnail']   = $this->thumbnail;
        $json['title']       = $this->title;
        $json['urls']        = $this->urls;

        return $json;
    }
}