<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Series implements JsonSerializable
{
    /**
     * The unique ID of the series resource.
     * @required
     * @var object $id public property
     */
    public $id;

    /**
     * The canonical title of the series.
     * @required
     * @var object $title public property
     */
    public $title;

    /**
     * A description of the series.
     * @required
     * @var object $description public property
     */
    public $description;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var object $resourceURI public property
     */
    public $resourceURI;

    /**
     * A set of public web site URLs for the resource.
     * @required
     * @var Url[] $urls public property
     */
    public $urls;

    /**
     * The first year of publication for the series.
     * @required
     * @var object $startYear public property
     */
    public $startYear;

    /**
     * The last year of publication for the series (conventionally, 2099 for ongoing series) .
     * @required
     * @var object $endYear public property
     */
    public $endYear;

    /**
     * The age-appropriateness rating for the series.
     * @required
     * @var object $rating public property
     */
    public $rating;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var object $modified public property
     */
    public $modified;

    /**
     * The representative image for this series.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * A resource list containing comics in this series.
     * @required
     * @var ComicList $comics public property
     */
    public $comics;

    /**
     * A resource list containing stories which occur in comics in this series.
     * @required
     * @var StoryList $stories public property
     */
    public $stories;

    /**
     * A resource list containing events which take place in comics in this series.
     * @required
     * @var EventList $events public property
     */
    public $events;

    /**
     * A resource list containing characters which appear in comics in this series.
     * @required
     * @var CharacterList $characters public property
     */
    public $characters;

    /**
     * A resource list of creators whose work appears in comics in this series.
     * @required
     * @var CreatorList $creators public property
     */
    public $creators;

    /**
     * A summary representation of the series which follows this series.
     * @required
     * @var SeriesSummary $next public property
     */
    public $next;

    /**
     * A summary representation of the series which preceded this series.
     * @required
     * @var SeriesSummary $previous public property
     */
    public $previous;

    /**
     * Constructor to set initial or default values of member properties
     * @param object        $id          Initialization value for $this->id
     * @param object        $title       Initialization value for $this->title
     * @param object        $description Initialization value for $this->description
     * @param object        $resourceURI Initialization value for $this->resourceURI
     * @param array         $urls        Initialization value for $this->urls
     * @param object        $startYear   Initialization value for $this->startYear
     * @param object        $endYear     Initialization value for $this->endYear
     * @param object        $rating      Initialization value for $this->rating
     * @param object        $modified    Initialization value for $this->modified
     * @param Thumbnail     $thumbnail   Initialization value for $this->thumbnail
     * @param ComicList     $comics      Initialization value for $this->comics
     * @param StoryList     $stories     Initialization value for $this->stories
     * @param EventList     $events      Initialization value for $this->events
     * @param CharacterList $characters  Initialization value for $this->characters
     * @param CreatorList   $creators    Initialization value for $this->creators
     * @param SeriesSummary $next        Initialization value for $this->next
     * @param SeriesSummary $previous    Initialization value for $this->previous
     */
    public function __construct()
    {
        if (17 == func_num_args()) {
            $this->id          = func_get_arg(0);
            $this->title       = func_get_arg(1);
            $this->description = func_get_arg(2);
            $this->resourceURI = func_get_arg(3);
            $this->urls        = func_get_arg(4);
            $this->startYear   = func_get_arg(5);
            $this->endYear     = func_get_arg(6);
            $this->rating      = func_get_arg(7);
            $this->modified    = func_get_arg(8);
            $this->thumbnail   = func_get_arg(9);
            $this->comics      = func_get_arg(10);
            $this->stories     = func_get_arg(11);
            $this->events      = func_get_arg(12);
            $this->characters  = func_get_arg(13);
            $this->creators    = func_get_arg(14);
            $this->next        = func_get_arg(15);
            $this->previous    = func_get_arg(16);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']          = $this->id;
        $json['title']       = $this->title;
        $json['description'] = $this->description;
        $json['resourceURI'] = $this->resourceURI;
        $json['urls']        = $this->urls;
        $json['startYear']   = $this->startYear;
        $json['endYear']     = $this->endYear;
        $json['rating']      = $this->rating;
        $json['modified']    = $this->modified;
        $json['thumbnail']   = $this->thumbnail;
        $json['comics']      = $this->comics;
        $json['stories']     = $this->stories;
        $json['events']      = $this->events;
        $json['characters']  = $this->characters;
        $json['creators']    = $this->creators;
        $json['next']        = $this->next;
        $json['previous']    = $this->previous;

        return $json;
    }
}
