<?php 
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Story implements JsonSerializable {
    /**
     * The unique ID of the story resource.
     * @required
     * @var int $id public property
     */
    public $id;

    /**
     * The story title.
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * A short description of the story.
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * The canonical URL identifier for this resource.
     * @required
     * @var string $resourceURI public property
     */
    public $resourceURI;

    /**
     * The story type e.g. interior story, cover, text story.
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * The date the resource was most recently modified.
     * @required
     * @var string $modified public property
     */
    public $modified;

    /**
     * The representative image for this story.
     * @required
     * @var Thumbnail $thumbnail public property
     */
    public $thumbnail;

    /**
     * A resource list containing comics in which this story takes place.
     * @required
     * @var ComicList $comics public property
     */
    public $comics;

    /**
     * A resource list containing series in which this story appears.
     * @required
     * @var SeriesList $series public property
     */
    public $series;

    /**
     * A resource list of the events in which this story appears.
     * @required
     * @var EventList $events public property
     */
    public $events;

    /**
     * A resource list of characters which appear in this story.
     * @required
     * @var CharacterList $characters public property
     */
    public $characters;

    /**
     * A resource list of creators who worked on this story.
     * @required
     * @var CreatorList $creators public property
     */
    public $creators;

    /**
     * A summary representation of the issue in which this story was originally published.
     * @required
     * @var ComicSummary $originalissue public property
     */
    public $originalissue;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   int               $id              Initialization value for the property $this->id           
	 * @param   string            $title           Initialization value for the property $this->title        
	 * @param   string            $description     Initialization value for the property $this->description  
	 * @param   string            $resourceURI     Initialization value for the property $this->resourceURI  
	 * @param   string            $type            Initialization value for the property $this->type         
	 * @param   string            $modified        Initialization value for the property $this->modified     
	 * @param   Thumbnail         $thumbnail       Initialization value for the property $this->thumbnail    
	 * @param   ComicList         $comics          Initialization value for the property $this->comics       
	 * @param   SeriesList        $series          Initialization value for the property $this->series       
	 * @param   EventList         $events          Initialization value for the property $this->events       
	 * @param   CharacterList     $characters      Initialization value for the property $this->characters   
	 * @param   CreatorList       $creators        Initialization value for the property $this->creators     
	 * @param   ComicSummary      $originalissue   Initialization value for the property $this->originalissue
     */
    public function __construct()
    {
        if(13 == func_num_args())
        {
            $this->id            = func_get_arg(0);
            $this->title         = func_get_arg(1);
            $this->description   = func_get_arg(2);
            $this->resourceURI   = func_get_arg(3);
            $this->type          = func_get_arg(4);
            $this->modified      = func_get_arg(5);
            $this->thumbnail     = func_get_arg(6);
            $this->comics        = func_get_arg(7);
            $this->series        = func_get_arg(8);
            $this->events        = func_get_arg(9);
            $this->characters    = func_get_arg(10);
            $this->creators      = func_get_arg(11);
            $this->originalissue = func_get_arg(12);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']            = $this->id;
        $json['title']         = $this->title;
        $json['description']   = $this->description;
        $json['resourceURI']   = $this->resourceURI;
        $json['type']          = $this->type;
        $json['modified']      = $this->modified;
        $json['thumbnail']     = $this->thumbnail;
        $json['comics']        = $this->comics;
        $json['series']        = $this->series;
        $json['events']        = $this->events;
        $json['characters']    = $this->characters;
        $json['creators']      = $this->creators;
        $json['originalissue'] = $this->originalissue;

        return $json;
    }
}