<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MarvelComicsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Thumbnail implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var object $path public property
     */
    public $path;

    /**
     * @todo Write general description for this property
     * @required
     * @var object $extension public property
     */
    public $extension;

    /**
     * Constructor to set initial or default values of member properties
     * @param object $path      Initialization value for $this->path
     * @param object $extension Initialization value for $this->extension
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->path      = func_get_arg(0);
            $this->extension = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['path']      = $this->path;
        $json['extension'] = $this->extension;

        return $json;
    }
}
