<?php
/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

namespace MarvelComicsLib;

use MarvelComicsLib\Controllers;

/**
 * MarvelComicsLib client class
 */
class MarvelComicsClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($referer = NULL, $apikey = NULL)
    {
        Configuration::$referer = $referer ? $referer : Configuration::$referer;
        Configuration::$apikey = $apikey ? $apikey : Configuration::$apikey;
    }
 
	/**
	 * Singleton access to Characters controller
	 * @return CharactersController The *Singleton* instance
	 */
	public function getCharacters()
	{
		return Controllers\CharactersController::getInstance();
	}
 
	/**
	 * Singleton access to Comics controller
	 * @return ComicsController The *Singleton* instance
	 */
	public function getComics()
	{
		return Controllers\ComicsController::getInstance();
	}
 
	/**
	 * Singleton access to Creators controller
	 * @return CreatorsController The *Singleton* instance
	 */
	public function getCreators()
	{
		return Controllers\CreatorsController::getInstance();
	}
 
	/**
	 * Singleton access to Events controller
	 * @return EventsController The *Singleton* instance
	 */
	public function getEvents()
	{
		return Controllers\EventsController::getInstance();
	}
 
	/**
	 * Singleton access to Series controller
	 * @return SeriesController The *Singleton* instance
	 */
	public function getSeries()
	{
		return Controllers\SeriesController::getInstance();
	}
 
	/**
	 * Singleton access to Stories controller
	 * @return StoriesController The *Singleton* instance
	 */
	public function getStories()
	{
		return Controllers\StoriesController::getInstance();
	}
}